#!/bin/bash

#Name: Le, Thanh Nhan

if [ $# -eq 0 ]; then
        echo "Error! No parameters passed in. Please provide a parameter when executing!"
        exit 1
fi

#Display the message "File Analysis"
echo "File Analysis"

#4.Display the message "Generated by: "
echo "Generated by:                  "$(logname)

#6.Display the message "Generated on: "
echo "Generated on:                  "$(date)

#8.Display the message "Lines with Numbers: "
echo "Lines with Numbers:            "$(grep [[:digit:]] $1 | wc -l)

#10.Display the message "Lines with Capitalized Words: "
echo "Lines with Capitalized Words:  "$(grep [[:upper:]] $1 | wc -l)

#11.Display the message "Lines with Palindromes: "
echo "Lines with Palindromes:        "$(grep -cE '\<([[:alpha:]])([[:alpha:]]?)([[:alpha:]]?)[[:alpha:]]?\3\2\1\>' "$1")

#14.Display the message "Blank Lines: "
echo "Blank Lines:                   "$(grep -cE "^[[:space:]]*$" $1)
